### ISSUE TITLE
shu yerda o'zi ajoyib bo'lib qolibdi nimaga bilmadm

### ISSUE THREAD

**Issue by AbdunazarovM** [oybek94/scooter#5]
![image](https://user-images.githubusercontent.com/79672855/117531736-79347600-affd-11eb-963b-eb03ef631748.png)
![image](https://user-images.githubusercontent.com/79672855/117532282-17294000-b000-11eb-8804-87f0b200f607.png)

**Comment by oybek94** [comment]
.content classiga height berilgan ekan shunga shunaqa mayda chuyda muammolar chiqibdi togirlandi raxmat
